[package]
name = "wasm-app"
version = "0.1.0"
authors = ["kylekosic <kylekosic@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
chrono = "0.4"
protobuf = "2.16"
yew = "0.17"
yewtil = "0.3"
wasm-bindgen = "0.2"
